name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- name: Azure Container Registry Login
    #  uses: Azure/docker-login@v1
    #  with:
    #    # Container registry username
    #    username: ${{ secrets.ACR_USERNAME }}
    #    # Container registry password
    #    password: ${{ secrets.ACR_PASSWORD }}
    #    # Container registry server url
    #    login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        echo ${{ secrets.PAT }} | docker login ghcr.io -u aaronba-va --password-stdin
        docker build . --file WebApp.Dockerfile --tag ghcr.io/aaronba-va/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ghcr.io/aaronba-va/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER fruoccopublic.azurecr.io/sample-app-aoai-chatgpt:latest;
        docker push ghcr.io/aaronba-va/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ghcr.io/aaronba-va/sample-app-aoai-chatgp:latest;
      
